export const data = [
    
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex, enim? Ducimus quasi, placeat et dicta quod earum molestias impedit repellat.",    
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex, enim? Ducimus quasi, placeat et dicta quod earum molestias impedit repellat.",
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex, enim? Ducimus quasi, placeat et dicta quod earum molestias impedit repellat.",
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex, enim? Ducimus quasi, placeat et dicta quod earum molestias impedit repellat.",
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex, enim? Ducimus quasi, placeat et dicta quod earum molestias impedit repellat.",
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex, enim? Ducimus quasi, placeat et dicta quod earum molestias impedit repellat.",
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex, enim? Ducimus quasi, placeat et dicta quod earum molestias impedit repellat.",
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex, enim? Ducimus quasi, placeat et dicta quod earum molestias impedit repellat.",
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex, enim? Ducimus quasi, placeat et dicta quod earum molestias impedit repellat.",
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex, enim? Ducimus quasi, placeat et dicta quod earum molestias impedit repellat.",
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex, enim? Ducimus quasi, placeat et dicta quod earum molestias impedit repellat.",
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex, enim? Ducimus quasi, placeat et dicta quod earum molestias impedit repellat.",
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex, enim? Ducimus quasi, placeat et dicta quod earum molestias impedit repellat.",
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex, enim? Ducimus quasi, placeat et dicta quod earum molestias impedit repellat.",
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex, enim? Ducimus quasi, placeat et dicta quod earum molestias impedit repellat.",
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex, enim? Ducimus quasi, placeat et dicta quod earum molestias impedit repellat.",
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex, enim? Ducimus quasi, placeat et dicta quod earum molestias impedit repellat.",
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex, enim? Ducimus quasi, placeat et dicta quod earum molestias impedit repellat.",
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex, enim? Ducimus quasi, placeat et dicta quod earum molestias impedit repellat.",
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex, enim? Ducimus quasi, placeat et dicta quod earum molestias impedit repellat.",
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex, enim? Ducimus quasi, placeat et dicta quod earum molestias impedit repellat.",
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex, enim? Ducimus quasi, placeat et dicta quod earum molestias impedit repellat.",
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex, enim? Ducimus quasi, placeat et dicta quod earum molestias impedit repellat.",
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex, enim? Ducimus quasi, placeat et dicta quod earum molestias impedit repellat.",
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex, enim? Ducimus quasi, placeat et dicta quod earum molestias impedit repellat.",
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex, enim? Ducimus quasi, placeat et dicta quod earum molestias impedit repellat.",

    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex, enim? Ducimus quasi, placeat et dicta quod earum molestias impedit repellat.",
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex, enim? Ducimus quasi, placeat et dicta quod earum molestias impedit repellat.",
]